// Données complètes des 114 sourates du Coran
export const SURAH_DATA = [
  { number: 1, frenchName: "L'Ouverture", englishName: "Al-Fatihah", duration: "0:46" },
  { number: 2, frenchName: "La Vache", englishName: "Al-Baqarah", duration: "1:57:34" },
  { number: 3, frenchName: "La Famille d'Imran", englishName: "Al-Imran", duration: "1:05:35" },
  { number: 4, frenchName: "Les Femmes", englishName: "An-Nisa'", duration: "1:13:07" },
  { number: 5, frenchName: "La Table Servie", englishName: "Al-Ma'idah", duration: "50:17" },
  { number: 6, frenchName: "Les Bestiaux", englishName: "Al-An'am", duration: "55:34" },
  { number: 7, frenchName: "Les Murailles", englishName: "Al-A'raf", duration: "1:04:14" },
  { number: 8, frenchName: "Le Butin", englishName: "Al-Anfal", duration: "22:34" },
  { number: 9, frenchName: "Le Repentir", englishName: "At-Tawbah", duration: "48:53" },
  { number: 10, frenchName: "Jonas", englishName: "Yunus", duration: "35:20" },
  { number: 11, frenchName: "Houd", englishName: "Hud", duration: "35:57" },
  { number: 12, frenchName: "Joseph", englishName: "Yusuf", duration: "32:15" },
  { number: 13, frenchName: "Le Tonnerre", englishName: "Ar-Ra'd", duration: "14:57" },
  { number: 14, frenchName: "Ibrahim", englishName: "Ibrahim", duration: "17:53" },
  { number: 15, frenchName: "Al-Hijr", englishName: "Al-Hijr", duration: "13:56" },
  { number: 16, frenchName: "Les Abeilles", englishName: "An-Nahl", duration: "34:10" },
  { number: 17, frenchName: "Le Voyage Nocturne", englishName: "Al-Isra", duration: "29:00" },
  { number: 18, frenchName: "La Caverne", englishName: "Al-Kahf", duration: "29:16" },
  { number: 19, frenchName: "Marie", englishName: "Maryam", duration: "17:36" },
  { number: 20, frenchName: "Tâ-Hâ", englishName: "Ta­Ha", duration: "22:41" },
  { number: 21, frenchName: "Les Prophètes", englishName: "Al-Anbiya'", duration: "25:11" },
  { number: 22, frenchName: "Le Pèlerinage", englishName: "Al-Hajj", duration: "24:54" },
  { number: 23, frenchName: "Les Croyants", englishName: "Al-Mu'minun", duration: "21:58" },
  { number: 24, frenchName: "La Lumière", englishName: "An-Nur", duration: "26:28" },
  { number: 25, frenchName: "Le Discernement", englishName: "Al-Furqan", duration: "16:38" },
  { number: 26, frenchName: "Les Poètes", englishName: "Ash-Shu'ara'", duration: "23:39" },
  { number: 27, frenchName: "Les Fourmis", englishName: "An-Naml", duration: "23:37" },
  { number: 28, frenchName: "Le Récit", englishName: "Al-Qasas", duration: "24:43" },
  { number: 29, frenchName: "L'Araignée", englishName: "Al-'Ankabut", duration: "19:58" },
  { number: 30, frenchName: "Les Byzantins", englishName: "Ar­Rum", duration: "14:48" },
  { number: 31, frenchName: "Luqman", englishName: "Luqman", duration: "9:27" },
  { number: 32, frenchName: "La Prosternation", englishName: "As­ Sajdah", duration: "7:08" },
  { number: 33, frenchName: "Les Coalisés", englishName: "Al­Ahzab", duration: "25:35" },
  { number: 34, frenchName: "Saba'", englishName: "Saba'", duration: "16:57" },
  { number: 35, frenchName: "Le Créateur", englishName: "Fatir", duration: "14:22" },
  { number: 36, frenchName: "Yâ-Sîn", englishName: "Ya­Sin", duration: "13:09" },
  { number: 37, frenchName: "Ceux qui se rangent en rangs", englishName: "As-Saffat", duration: "17:48" },
  { number: 38, frenchName: "Sâd", englishName: "Sad", duration: "14:41" },
  { number: 39, frenchName: "Les Groupes", englishName: "Az-Zumar", duration: "23:33" },
  { number: 40, frenchName: "Le Croyant", englishName: "Ghafir", duration: "22:15" },
  { number: 41, frenchName: "Fussilat", englishName: "Fussilat", duration: "15:21" },
  { number: 42, frenchName: "La Concertation", englishName: "Ash-Shura", duration: "15:26" },
  { number: 43, frenchName: "L'Ornement", englishName: "Az-Zukhruf", duration: "16:41" },
  { number: 44, frenchName: "La Fumée", englishName: "Ad-Dukhan", duration: "6:52" },
  { number: 45, frenchName: "L'Agenouillée", englishName: "Al-Jathiya", duration: "9:00" },
  { number: 46, frenchName: "Les Dunes", englishName: "Al-Ahqaf", duration: "11:56" },
  { number: 47, frenchName: "Muhammad", englishName: "Muhammad", duration: "9:51" },
  { number: 48, frenchName: "La Victoire", englishName: "Al-Fath", duration: "10:21" },
  { number: 49, frenchName: "Les Appartements", englishName: "Al-Hujurat", duration: "6:29" },
  { number: 50, frenchName: "Qâf", englishName: "Qaf", duration: "7:17" },
  { number: 51, frenchName: "Les Vents Dispersants", englishName: "Az-Zariyat", duration: "6:55" },
  { number: 52, frenchName: "Le Mont", englishName: "At-Tur", duration: "6:03" },
  { number: 53, frenchName: "L'Étoile", englishName: "An-Najm", duration: "7:10" },
  { number: 54, frenchName: "La Lune", englishName: "Al-Qamar", duration: "6:36" },
  { number: 55, frenchName: "Le Miséricordieux", englishName: "Ar-Rahman", duration: "8:31" },
  { number: 56, frenchName: "L'Inéluctable", englishName: "Al-Waqi'ah", duration: "8:23" },
  { number: 57, frenchName: "Le Fer", englishName: "Al-Hadid", duration: "11:15" },
  { number: 58, frenchName: "La Controverse", englishName: "Al-Mujadilah", duration: "8:48" },
  { number: 59, frenchName: "Le Rassemblement", englishName: "Al-Hashr", duration: "8:22" },
  { number: 60, frenchName: "La Mise à l'Épreuve", englishName: "Al-Mumtahinah", duration: "6:58" },
  { number: 61, frenchName: "La Rangée", englishName: "As-Saff", duration: "4:10" },
  { number: 62, frenchName: "Le Vendredi", englishName: "Al-Jumu'ah", duration: "3:10" },
  { number: 63, frenchName: "Les Hypocrites", englishName: "Al-Munafiqun", duration: "3:19" },
  { number: 64, frenchName: "La Spoliation", englishName: "At-Taghabun", duration: "4:30" },
  { number: 65, frenchName: "Le Divorce", englishName: "At-Talaq", duration: "5:20" },
  { number: 66, frenchName: "L'Interdiction", englishName: "At-Tahrim", duration: "4:51" },
  { number: 67, frenchName: "Le Royaume", englishName: "Al-Mulk", duration: "6:24" },
  { number: 68, frenchName: "La Plume", englishName: "Al-Qalam", duration: "5:57" },
  { number: 69, frenchName: "La Réalité", englishName: "Al-Haqqah", duration: "5:30" },
  { number: 70, frenchName: "Les Degrés d'Élévation", englishName: "Al-Ma'arij", duration: "4:39" },
  { number: 71, frenchName: "Noé", englishName: "Nuh", duration: "4:22" },
  { number: 72, frenchName: "Les Djinns", englishName: "Al-Jinn", duration: "5:04" },
  { number: 73, frenchName: "L'Enveloppé", englishName: "Al-Muzzammil", duration: "3:54" },
  { number: 74, frenchName: "Le Revêtu d'un Manteau", englishName: "Al-Muddaththir", duration: "4:59" },
  { number: 75, frenchName: "La Résurrection", englishName: "Al-Qiyamah", duration: "3:00" },
  { number: 76, frenchName: "L'Homme", englishName: "Al-Insan", duration: "4:45" },
  { number: 77, frenchName: "Ceux qu'on Envoie", englishName: "Al-Mursalat", duration: "4:02" },
  { number: 78, frenchName: "La Nouvelle", englishName: "An-Naba'", duration: "3:59" },
  { number: 79, frenchName: "Ceux qui Arrachent", englishName: "An-Nazi'at", duration: "3:39" },
  { number: 80, frenchName: "Il s'est Renfrogné", englishName: "'Abasa", duration: "3:05" },
  { number: 81, frenchName: "L'Obscurcissement", englishName: "At-Takwir", duration: "2:03" },
  { number: 82, frenchName: "L'Éclatement", englishName: "Al-Infitar", duration: "1:41" },
  { number: 83, frenchName: "Ceux qui Lésinent", englishName: "Al-Mutaffifin", duration: "3:46" },
  { number: 84, frenchName: "La Fission", englishName: "Al-Inshiqaq", duration: "2:06" },
  { number: 85, frenchName: "Les Constellations", englishName: "Al-Buruj", duration: "2:17" },
  { number: 86, frenchName: "L'Astre Nocturne", englishName: "At-Tariq", duration: "1:15" },
  { number: 87, frenchName: "Le Très-Haut", englishName: "Al-A'la", duration: "1:20" },
  { number: 88, frenchName: "L'Enveloppant", englishName: "Al-Ghashiyah", duration: "1:52" },
  { number: 89, frenchName: "L'Aube", englishName: "Al-Fajr", duration: "2:51" },
  { number: 90, frenchName: "La Cité", englishName: "Al-Balad", duration: "1:35" },
  { number: 91, frenchName: "Le Soleil", englishName: "Ash-Shams", duration: "1:10" },
  { number: 92, frenchName: "La Nuit", englishName: "Al-Lail", duration: "1:31" },
  { number: 93, frenchName: "Le Matin", englishName: "Ad-Duha", duration: "0:52" },
  { number: 94, frenchName: "L'Expansion", englishName: "Ash-Sharh", duration: "0:31" },
  { number: 95, frenchName: "Le Figuier", englishName: "At-Tin", duration: "0:47" },
  { number: 96, frenchName: "Le Caillot de Sang", englishName: "Al-'Alaq", duration: "1:21" },
  { number: 97, frenchName: "La Nuit du Destin", englishName: "Al-Qadr", duration: "0:36" },
  { number: 98, frenchName: "La Preuve", englishName: "Al-Baiyinah", duration: "1:50" },
  { number: 99, frenchName: "Le Tremblement de Terre", englishName: "Az-Zalzalah", duration: "0:47" },
  { number: 100, frenchName: "Les Poulains", englishName: "Al- Adiyat", duration: "0:55" },
  { number: 101, frenchName: "Le Fracas", englishName: "Al-Qari'ah", duration: "0:49" },
  { number: 102, frenchName: "La Rivalité", englishName: "At-Takathur", duration: "0:43" },
  { number: 103, frenchName: "L'Après-Midi", englishName: "Al-'Asr", duration: "0:20" },
  { number: 104, frenchName: "Le Calomniateur", englishName: "Al-Humazah", duration: "0:43" },
  { number: 105, frenchName: "L'Éléphant", englishName: "Al-Fil", duration: "0:31" },
  { number: 106, frenchName: "Qoraych", englishName: "Quaysh", duration: "0:30" },
  { number: 107, frenchName: "L'Ustensile", englishName: "Al-Ma'un", duration: "0:39" },
  { number: 108, frenchName: "L'Abondance", englishName: "Al-Kauthar", duration: "0:17" },
  { number: 109, frenchName: "Les Infidèles", englishName: "Al-Kafirun", duration: "0:38" },
  { number: 110, frenchName: "Le Secours", englishName: "An-Nasr", duration: "0:26" },
  { number: 111, frenchName: "Les Fibres", englishName: "Al-Masad", duration: "0:30" },
  { number: 112, frenchName: "La Pureté", englishName: "Al-Ikhlas", duration: "0:16" },
  { number: 113, frenchName: "L'Aube Naissante", englishName: "Al-Falaq", duration: "0:27" },
  { number: 114, frenchName: "Les Hommes", englishName: "An-Nas", duration: "0:34" },
];

// Fonction helper pour obtenir les données d'une sourate
export const getSurahData = (surahNumber) => {
  return SURAH_DATA.find(surah => surah.number === parseInt(surahNumber));
};
